INSERT INTO public.ingredients (slug, name, category, aisle, base_unit, pack_qty, pack_price, allergens, diet_flags) VALUES
('oeuf','Œufs','proteine','Crèmerie','piece',6,2.10,'{oeuf}','{vegetarien}'),
('lait','Lait demi-écrémé','laitier','Crèmerie','ml',1000,1.15,'{lait}','{vegetarien}'),
('yaourt-nature','Yaourt nature','laitier','Crèmerie','piece',4,1.60,'{lait}','{vegetarien}'),
('fromage-rape','Fromage râpé','laitier','Crèmerie','g',200,2.20,'{lait}','{vegetarien}'),
('feta','Feta','laitier','Crèmerie','g',200,2.60,'{lait}','{vegetarien}'),
('beurre','Beurre','laitier','Crèmerie','g',250,2.40,'{lait}','{vegetarien}'),
('creme-fraiche','Crème fraîche','laitier','Crèmerie','ml',200,1.30,'{lait}','{vegetarien}'),
('poulet-filet','Filet de poulet','proteine','Boucherie','g',500,6.50,'{}','{halal_possible}'),
('boeuf-hache','Bœuf haché','proteine','Boucherie','g',500,6.90,'{}','{}'),
('dinde-hachee','Dinde hachée','proteine','Boucherie','g',400,5.20,'{}','{}'),
('saumon','Pavé de saumon','proteine','Poissonnerie','g',300,7.80,'{poisson}','{pescetarien}'),
('thon-boite','Thon en boîte','proteine','Épicerie','g',280,3.10,'{poisson}','{pescetarien}'),
('sardines','Sardines en boîte','proteine','Épicerie','g',240,2.40,'{poisson}','{pescetarien}'),
('tofu','Tofu ferme','proteine','Épicerie','g',250,2.30,'{soja}','{vegan}'),
('pois-chiches','Pois chiches','proteine','Épicerie','g',400,1.10,'{}','{vegan}'),
('lentilles','Lentilles vertes','proteine','Épicerie','g',500,2.00,'{}','{vegan}'),
('haricots-rouges','Haricots rouges','proteine','Épicerie','g',400,1.20,'{}','{vegan}'),
('riz','Riz long','feculent','Épicerie','g',1000,1.90,'{}','{vegan}'),
('pates','Pâtes','feculent','Épicerie','g',500,1.20,'{gluten}','{vegetarien}'),
('semoule','Semoule de couscous','feculent','Épicerie','g',500,1.40,'{gluten}','{vegan}'),
('quinoa','Quinoa','feculent','Épicerie','g',500,3.40,'{}','{vegan}'),
('pomme-de-terre','Pommes de terre','legume','Fruits & légumes','g',2500,3.20,'{}','{vegan}'),
('patate-douce','Patate douce','legume','Fruits & légumes','g',1000,2.60,'{}','{vegan}'),
('pain-complet','Pain complet','feculent','Boulangerie','g',500,1.80,'{gluten}','{vegan}'),
('tortilla','Tortillas de blé','feculent','Épicerie','piece',8,1.90,'{gluten}','{vegan}'),
('farine','Farine de blé','feculent','Épicerie','g',1000,1.10,'{gluten}','{vegan}'),
('flocons-avoine','Flocons d''avoine','feculent','Épicerie','g',500,1.60,'{gluten}','{vegan}'),
('oignon','Oignons','legume','Fruits & légumes','g',1000,1.60,'{}','{vegan}'),
('ail','Ail','legume','Fruits & légumes','piece',3,0.90,'{}','{vegan}'),
('carotte','Carottes','legume','Fruits & légumes','g',1000,1.40,'{}','{vegan}'),
('courgette','Courgettes','legume','Fruits & légumes','g',1000,2.20,'{}','{vegan}'),
('poivron','Poivrons','legume','Fruits & légumes','piece',3,2.40,'{}','{vegan}'),
('tomate','Tomates','legume','Fruits & légumes','g',1000,2.60,'{}','{vegan}'),
('tomates-concassees','Tomates concassées','legume','Épicerie','g',400,1.00,'{}','{vegan}'),
('epinards','Épinards','legume','Fruits & légumes','g',500,2.50,'{}','{vegan}'),
('brocoli','Brocoli','legume','Fruits & légumes','g',500,2.10,'{}','{vegan}'),
('champignons','Champignons de Paris','legume','Fruits & légumes','g',500,2.60,'{}','{vegan}'),
('salade','Salade verte','legume','Fruits & légumes','piece',1,1.20,'{}','{vegan}'),
('concombre','Concombre','legume','Fruits & légumes','piece',1,1.10,'{}','{vegan}'),
('citron','Citrons','fruit','Fruits & légumes','piece',4,1.80,'{}','{vegan}'),
('banane','Bananes','fruit','Fruits & légumes','g',1000,1.70,'{}','{vegan}'),
('pomme','Pommes','fruit','Fruits & légumes','g',1000,2.30,'{}','{vegan}'),
('fruits-rouges-surgeles','Fruits rouges surgelés','fruit','Surgelés','g',450,3.20,'{}','{vegan}'),
('petits-pois-surgeles','Petits pois surgelés','legume','Surgelés','g',750,1.90,'{}','{vegan}'),
('huile-olive','Huile d''olive','condiment','Épicerie','ml',750,6.50,'{}','{vegan}'),
('huile-tournesol','Huile de tournesol','condiment','Épicerie','ml',1000,2.40,'{}','{vegan}'),
('sel','Sel','condiment','Épicerie','g',500,0.60,'{}','{vegan}'),
('poivre','Poivre','condiment','Épicerie','g',50,1.90,'{}','{vegan}'),
('paprika','Paprika','condiment','Épicerie','g',40,1.50,'{}','{vegan}'),
('cumin','Cumin','condiment','Épicerie','g',40,1.50,'{}','{vegan}'),
('curry','Curry','condiment','Épicerie','g',40,1.60,'{}','{vegan}'),
('herbes-provence','Herbes de Provence','condiment','Épicerie','g',30,1.40,'{}','{vegan}'),
('bouillon-legumes','Bouillon de légumes','condiment','Épicerie','piece',10,1.30,'{}','{vegan}'),
('sauce-soja','Sauce soja','condiment','Épicerie','ml',250,2.20,'{soja,gluten}','{vegan}'),
('lait-coco','Lait de coco','condiment','Épicerie','ml',400,1.70,'{}','{vegan}'),
('miel','Miel','condiment','Épicerie','g',250,3.60,'{}','{vegetarien}'),
('sucre','Sucre','condiment','Épicerie','g',1000,1.20,'{}','{vegan}'),
('beurre-cacahuete','Beurre de cacahuète','condiment','Épicerie','g',350,3.40,'{arachide}','{vegan}'),
('amandes','Amandes','autre','Épicerie','g',200,3.20,'{fruits_a_coque}','{vegan}'),
('chocolat-noir','Chocolat noir','autre','Épicerie','g',200,2.10,'{}','{vegan}'),
('houmous','Houmous','autre','Crèmerie','g',200,2.00,'{sesame}','{vegan}'),
('olives','Olives','autre','Épicerie','g',200,2.20,'{}','{vegan}');

INSERT INTO public.stores (brand, country, city, price_index) VALUES
('Carrefour','FR','Paris',1.00),
('Lidl','FR','Paris',0.86),
('Aldi','FR','Paris',0.85),
('Leclerc','FR','Lyon',0.92),
('Intermarché','FR','Lille',0.96),
('Monoprix','FR','Paris',1.18),
('Auchan','FR','Marseille',0.95),
('Delhaize','BE','Bruxelles',1.05),
('Colruyt','BE','Anvers',0.90),
('Migros','CH','Genève',1.35),
('Metro','CA','Montréal',1.10);